### ISSUE TITLE
Discussion: Should we add a new operator '//' that is specifically for dividing integers?

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#44]
This is how python does it. The benefit of it is that something `5 / 2` is no longer ambiguous. If `/` is for integer division and float division then `5/2` could equal either `2.5` or `2`, if we create a new operator then `5 / 2` always equals `2.5`  and `5 // 2` always equals `2`.

@ayazhafiz @ema-fox, what do you think?

**Comment by ayazhafiz** [comment]
What happens if you do // with two FPs?

I think we need to think about math ops more generally first. Should we allow operation between any two number types? If so, what is the resulting type? If we only allow operations between the same types then this will be more user code but more deterministic.

________________________________
От: lukasberglund <notifications@github.com>
Отправлено: Monday, March 30, 2020 8:44:56 AM
Кому: ayazhafiz/hgb <hgb@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Mention <mention@noreply.github.com>
Тема: [ayazhafiz/hgb] Discussion: Should we add a new operator '//' that is specifically for dividing integers? (#44)


This is how python does it. The benefit of it is that something 5 / 2 is no longer ambiguous. If / is for integer division and float division then 5/2 could equal either 2.5 or 2, if we create a new operator then 5 / 2 always equals 2.5 and 5 // 2 always equals 2.

@ayazhafiz<https://github.com/ayazhafiz> @ema-fox<https://github.com/ema-fox>, what do you think?

**Comment by lukasberglund** [comment]
I think in that case we have to think about our language more generally first. Should we build a relatively low level language or a high-level one? Should we go for ease of use or control?

**Comment by ayazhafiz** [comment]
I think we should aim for some paradigm like Rust and Haskell.

**Comment by lukasberglund** [comment]
Can you elaborate?

**Comment by ayazhafiz** [comment]
I suggest

- Supporting functional and OO (polymorphism) paradigms, possibly via a prominent Actor model
- Strong type safety (explicit casts, no implicit type erasure)
- Target general-purpose applications (e.g. rather than just scripts)
- Lazy evaluation by default

More on the compiler side:

- Include a standard library

I will add more if I think of it...

**Comment by ema-fox** [comment]
Usually in statically typed languages the default divide operator determines the result type from the operand types. In this case divide two integers with the result a float would be the special case. It would be quite easy to write a function with such a behavior so I don't think it's worth it to include it in the language itself.

**Comment by lukasberglund** [comment]
That's true, but it would still make the code clearer I think. You would be able to tell right away by the type of symbol (either `/` or `//`) whether the result of an operation is a float or an int. Plus when you want to divide numbers you typed (say you want to get 1/3) you could just write `1 / 3` instead of having to force the enumerator to be a float by writing `1.0 / 3`.

**Comment by ayazhafiz** [comment]
What would 32u64 // 5i16 evaluate to? What would 32.32f64 // 5i16 evaluate to?

________________________________
От: lukasberglund <notifications@github.com>
Отправлено: Tuesday, March 31, 2020 12:49:19 AM
Кому: ayazhafiz/hgb <hgb@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Mention <mention@noreply.github.com>
Тема: Re: [ayazhafiz/hgb] Discussion: Should we add a new operator '//' that is specifically for dividing integers? (#44)


That's true, but it would still make the code clearer I think. You would be able to tell right away by the type of symbol (either / or //) whether the result of an operation is a float or an int. Plus when you want to divide numbers you typed (say you want to get 1/3) you could just write 1 / 3 instead of having to force the enumerator to be a float by writing 1.0 / 3.

**Comment by lukasberglund** [comment]
I don't know about the first example, but in the second example I would say it would throw an error since `//` only works on ints. The first example depends on whether we want to allow doing math with different integer types. What do you think?
